name: show-git-ops
on:
  push: {}
  workflow_dispatch:
    inputs:
      tag:
        description: 'タグ'
        required: true
        default: '0000'
        type: string
      depth:
        description: 'number of git logs'
        required: true
        type: integer

jobs:
  show:
    name: show
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "${{ fromJSON(inputs.depth) }}"

      - name: time of now
        id: now
        run: TZ=JST-9 date "+%Y%m%d.%H.%M"

      - name: show github event
        run: echo "${EVENT}"
        env:
          EVENT: ${{ toJSON(github.event) }}

      - name: run git branches
        run: git branch --all

      - name: run git log
        run: git log -n 5 --oneline
